#!/bin/bash

module="$(pwd)/module"
rm -rf ${module}
wget -O ${module} "https://raw.githubusercontent.com/rudi9999/Herramientas/main/module/module" &>/dev/null
[[ ! -e ${module} ]] && exit
chmod +x ${module} &>/dev/null
source ${module}

echo "$$" >/etc/SCRIPT-LATAM/temp/menuid
clear && clear
echo -e "\a\a\a"
check-update
if [ $(whoami) != 'root' ]; then #-- VERIFICAR ROOT
  echo -e "\033[1;31m -- NECESITAS SER USER ROOT PARA EJECUTAR EL SCRIPT --\n\n\033[97m                DIGITE: \033[1;32m sudo su; menu\n"
  sleep 5s
  exit && exit
fi
rebootnb "totallssh" & ##-->> CONTADOR DE SSH
##-->> COLORES
red=$(tput setaf 1)
gren=$(tput setaf 2)
yellow=$(tput setaf 3)
SCPdir="/etc/SCRIPT-LATAM" && [[ ! -d ${SCPdir} ]] && exit 1
SCTemp="/etc/SCRIPT-LATAM/temp" && [[ ! -d ${SCTemp} ]] && exit 1
SCPfrm="${SCPdir}/botmanager"
if [[ -e /etc/bash.bashrc-bakup ]]; then # -- CHECK AUTORUN
  AutoRun="\033[1;93m[\033[1;32m ON \033[1;93m]"
elif [[ -e /etc/bash.bashrc ]]; then
  AutoRun="\033[1;93m[\033[1;31m OFF \033[1;93m]"
fi
msg() { ##-->> COLORES, TITULO, BARRAS
  ##-->> ACTULIZADOR Y VERCION
  [[ ! -e /etc/SCRIPT-LATAM/temp/version_instalacion ]] && printf '1\n' >/etc/SCRIPT-LATAM/temp/version_instalacion
  v11=$(cat /etc/SCRIPT-LATAM/temp/version_actual)
  v22=$(cat /etc/SCRIPT-LATAM/temp/version_instalacion)
  if [[ $v11 = $v22 ]]; then
    vesaoSCT="\e[1;31m[\033[1;37m Ver.\033[1;32m $v22 \033[1;31m]"
  else
    vesaoSCT="\e[1;31m[\e[31m ACTUALIZAR \e[25m\033[1;31m]"
  fi
  ##-->> COLORES
  local colors="/etc/SCRIPT-LATAM/colors"
  if [[ ! -e $colors ]]; then
    COLOR[0]='\033[1;37m' #GRIS='\033[1;37m'
    COLOR[1]='\e[31m'     #ROJO='\e[31m'
    COLOR[2]='\e[32m'     #VERDE='\e[32m'
    COLOR[3]='\e[33m'     #AMARILLO='\e[33m'
    COLOR[4]='\e[34m'     #AZUL='\e[34m'
    COLOR[5]='\e[91m'     #ROJO-NEON='\e[91m'
    COLOR[6]='\033[1;97m' #BALNCO='\033[1;97m'

  else
    local COL=0
    for number in $(cat $colors); do
      case $number in
      1) COLOR[$COL]='\033[1;37m' ;;
      2) COLOR[$COL]='\e[31m' ;;
      3) COLOR[$COL]='\e[32m' ;;
      4) COLOR[$COL]='\e[33m' ;;
      5) COLOR[$COL]='\e[34m' ;;
      6) COLOR[$COL]='\e[35m' ;;
      7) COLOR[$COL]='\033[1;36m' ;;
      esac
      let COL++
    done
  fi
  NEGRITO='\e[1m'
  SINCOLOR='\e[0m'
  case $1 in
  -ne) cor="${COLOR[1]}${NEGRITO}" && echo -ne "${cor}${2}${SINCOLOR}" ;;
  -ama) cor="${COLOR[3]}${NEGRITO}" && echo -e "${cor}${2}${SINCOLOR}" ;;
  -verm) cor="${COLOR[3]}${NEGRITO}[!] ${COLOR[1]}" && echo -e "${cor}${2}${SINCOLOR}" ;;
  -verm2) cor="${COLOR[1]}${NEGRITO}" && echo -e "${cor}${2}${SINCOLOR}" ;;
  -azu) cor="${COLOR[6]}${NEGRITO}" && echo -e "${cor}${2}${SINCOLOR}" ;;
  -verd) cor="${COLOR[2]}${NEGRITO}" && echo -e "${cor}${2}${SINCOLOR}" ;;
  -bra) cor="${COLOR[0]}${SINCOLOR}" && echo -e "${cor}${2}${SINCOLOR}" ;;
  "-bar2" | "-bar") cor="${COLOR[1]}════════════════════════════════════════════════════" && echo -e "${SINCOLOR}${cor}${SINCOLOR}" ;;
  # Centrar texto
  -tit) echo -e " \e[48;5;214m\e[38;5;0m   💻 𝙎 𝘾 𝙍 𝙄 𝙋 𝙏 | 𝙇 𝘼 𝙏 𝘼 𝙈 💻   \e[0m  $vesaoSCT" ;;
  esac
}
#--- INFO DE SISTEMA
os_system() {
  system=$(echo $(cat -n /etc/issue | grep 1 | cut -d' ' -f6,7,8 | sed 's/1//' | sed 's/      //'))
  echo $system | awk '{print $1, $2}'
}
#--- FUNCION IP INSTALACION
meu_ip() {
  if [[ -e /tmp/IP ]]; then
    echo "$(cat /tmp/IP)"
  else
    MEU_IP=$(wget -qO- ifconfig.me)
    echo "$MEU_IP" >/tmp/IP
  fi
}


drowkid(){ source <(curl -sSL https://gitlab.com/fdarnix/chukkmod-files/-/raw/main/source/$1) $2 ;read -p " Enter" ; }

#--- FUNCION IP ACTUAL
fun_ip() {
  if [[ -e /etc/SCRIPT-LATAM/MEUIPvps ]]; then
    IP="$(cat /etc/SCRIPT-LATAM/MEUIPvps)"
  else
    MEU_IP=$(wget -qO- ifconfig.me)
    echo "$MEU_IP" >/etc/SCRIPT-LATAM/MEUIPvps
  fi
}

#--- MENU DE SELECCION
selection_fun() {
  local selection
  local options="$(seq 0 $1 | paste -sd "," -)"
  read -p $'\033[1;97m  └⊳ Seleccione una opción:\033[1;32m ' selection
  if [[ $options =~ (^|[^\d])$selection($|[^\d]) ]]; then
    echo $selection
  else
    echo "Selección no válida: $selection" >&2
    exit 1
  fi
}

in_opcion(){
  unset opcion
  if [[ -z $2 ]]; then
      msg -nazu " $1: " >&2
  else
      msg $1 " $2: " >&2
  fi
  read opcion
  echo "$opcion"
}

export -f msg
export -f selection_fun
export -f meu_ip
export -f fun_ip
clear && clear

fun_bar() {
  comando="$1"
  _=$(
    $comando >/dev/null 2>&1
  ) &
  >/dev/null
  pid=$!
  while [[ -d /proc/$pid ]]; do
    echo -ne " \033[1;33m["
    for ((i = 0; i < 20; i++)); do
      echo -ne "\033[1;31m##"
      sleep 0.2
    done
    echo -ne "\033[1;33m]"
    sleep 1s
    echo
    tput cuu1
    tput dl1
  done
  echo -ne " \033[1;33m[\033[1;31m########################################\033[1;33m] - \033[1;32m100%\033[0m\n"
  sleep 1s
}

service_badvpn(){

	echo -e "[Unit]
Description=BadVPN UDPGW Service
After=network.target\n
[Service]
Type=simple
User=root
WorkingDirectory=/root
ExecStart=/usr/bin/badvpn-udpgw --listen-addr 127.0.0.1:$1 --max-clients 1000 --max-connections-for-client 10
Restart=always
RestartSec=3s\n
[Install]
WantedBy=multi-user.target" > /etc/systemd/system/badvpn.$1.service

	systemctl enable badvpn.$1 &>/dev/null
    systemctl start badvpn.$1 &>/dev/null

    if [[ $(systemctl is-active badvpn.$1) = 'active' ]]; then
    	echo 'active'
    else
    	echo 'inactive'
    fi
}

IN_PORT(){
	while [[ -z $_PORT ]]; do
		read -rp " $(msg -ama "INGRESE UN PUERTO [DEFAULT 7300]:") " -e -i  7300 _PORT
		del 1
		if [[ -z $_PORT ]]; then
			_PORT='7300'
		elif [[ ! $_PORT =~ $numero ]]; then
			print_center -verm2 'ingresa solo numeros'
			sleep 2
			unset _PORT
			del 1
			continue
		fi

		TTOTAL=($_PORT)
  		for((i=0; i<${#TTOTAL[@]}; i++)); do
  			[[ $(mportas|grep "${TTOTAL[$i]}") = "" ]] && {
  				echo " $(msg -azu 'Puerto Elegido:') $(msg -verd "${TTOTAL[$i]} OK")"
  				PORT="$PORT ${TTOTAL[$i]}"
  			} || {
  				echo " $(msg -azu 'Puerto Elegido:') $(msg -verm2 "${TTOTAL[$i]} FAIL")"
  			}
  		done

  		[[ -z $PORT ]] && {
  			msg -bar
  			print_center -verm2 'Ningun Puerto Valida Fue Elegido'
  			sleep 2
  			del $((${#TTOTAL[@]} + 2))
  			unset _PORT
  			unset PORT
  			continue
  		}
	done
	unset _PORT
}

install(){
	clr(){
		cd $HOME
        rm -rf ${ADM_src}/badvpn-master*
	}
	if [[ $(type -p badvpn-udpgw) ]]; then
		_services=$(systemctl list-unit-files|grep badvpn|awk '{print $1}')

		print_center -ama 'REMOVIENDO BADVPN'
		while [[ ! -z $_services ]] && read line; do
			systemctl stop $line &>/dev/null
			systemctl disable $line &>/dev/null
		done <<< $(echo "$_services")
		rm -rf /etc/systemd/system/badvpn*
		rm -rf $(type -p badvpn-udpgw)
		del 1
		print_center -verd 'BADVPN REMOVIDO!!!'
		enter
	else
		title 'instalador badvpn-udpgw by @Rufu99'
		IN_PORT
		msg -bar
		print_center -ama "INSTALADO BADVPN"
		msg -bar
		rm -rf ${ADM_src}/badvpn-master*
		msg -nazu " INSTALADO DEPENDECIAS... "
		if apt install cmake -y &>/dev/null; then
			msg -verd "[OK]"
		else
			del 1
            print_center -verm2 'FALLA AL INSTALAR DEPENDENCIAS "cmake"\nINTENTE INSTALAR DE FORMA MANUAL\n\napt install cmake\n\nE INTENTE NUEVAMENTE'
            enter
            return
        fi

        cd ${ADM_src}
        msg -nazu " DESCARGANDO BADVPN...... "
        if wget https://github.com/rudi9999/ADMRufu/raw/main/Utils/badvpn/badvpn-master.zip &>/dev/null; then
            msg -verd "[OK]"
        else
        	clr
        	del 1
        	print_center -verm2 'FALLA AL DESCARGAR BADVPN'
            enter
            return
        fi

        msg -nazu " DESCOMPRIMIENDO......... "
        if unzip badvpn-master.zip &>/dev/null; then
            msg -verd "[OK]"
        else
        	clr
        	del 1
            print_center -verm2 'FALLA AL DESCOMPRIMIR PAQUETE ZIP'
            enter
            return
        fi

        msg -nazu " COMPILANDO BADVPN....... "

        cd badvpn-master
        mkdir build
        cd build

        if cmake .. -DCMAKE_INSTALL_PREFIX="/" -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1 &>/dev/null ; then
            msg -verd "[OK]"
        else
        	clr
        	del 1
            print_center -verm2 'FALLA DE COMPILACION'
            enter
            return 1
        fi

        msg -nazu ' INSTALANDO.............. '
        if make install &>/dev/null; then
        	msg -verd "[OK]"
        else
        	clr
        	del 1
        	print_center -verm2 'FALLA DE INSTALACION'
        	enter
        	return
        fi
        clr

        msg -nazu ' INICIANDO............... '
        if [[ $(service_badvpn $PORT) = 'active' ]]; then
        	msg -verd "[OK]"
        else
        	del 1
        	print_center -verm2 'FALLA AL INICIAR SERVICIO BADVPN'
        fi
        enter
	fi
}

all_service(){
	n=1
	while read line; do
		serv_por[$n]=$line
		viw_port=$(echo "$line"|awk -F '.' '{print $2}')
		if [[ $(systemctl is-active $line) = 'active' ]]; then
			sta="\e[1m\e[32mON"
		else
			sta="\e[1m\e[31mOFF"
		fi
		echo -e " $(msg -verd "[$n]") $(msg -verm2 '>') $(msg -azu "$viw_port") $sta"
		let n++
	done <<< $(echo "$_services")

}

restart(){
	print_center -ama 'BUSCANDO SERVICIOS...'
	_services=$(systemctl list-unit-files|grep badvpn|awk '{print $1}')
	#_services=$(systemctl --all|grep badvpn|awk '{print $1}')
	if [[ $(echo "$_services"|wc -l) = 1 ]]; then
		if [[ $(systemctl is-enabled $_services) = 'disabled' ]]; then
			systemctl enable $_services &>/dev/null
		fi
		systemctl restart $_services &>/dev/null
		del 1
		print_center -verd 'BADVPN REINICIADO!!!'
		enter
		return
	fi
	title 'REINICIO DE SERVICIOS'
	all_service
	echo " $(msg -verd "[$n]") $(msg -verm2 '>') $(msg -azu 'REINICIAR TODOS')"
	back
	_opcion=$(selection_fun $n)
	[[ $_opcion = 0 ]] && return
	print_center -ama 'REINICIANDO BADVPN'
	while [[ $_opcion = $n ]] && read line; do
		if [[ $(systemctl is-enabled $line) = 'enabled' ]]; then
			systemctl enable $line &>/dev/null
		fi
		systemctl restart $line &>/dev/null
	done <<< $(echo "${serv_por[@]}")
	if [[ ! $_opcion = $n ]]; then
		if [[ $(systemctl is-enabled ${serv_por[$_opcion]}) = 'disabled' ]]; then
			systemctl enable ${serv_por[$_opcion]} &>/dev/null
		fi
		systemctl restart ${serv_por[$_opcion]} &>/dev/null
	fi
	del 1
	print_center -verd 'BADVPN REINICIADO'
	enter
}

stop(){
	#_services=$(systemctl list-unit-files|grep badvpn|awk '{print $1}')
	#_services=$(systemctl list-units --type=service|grep badvpn|awk '{print $1}')
	_services=$(systemctl list-units --all --state=active|grep badvpn|awk '{print $1}')
	if [[ $(echo "$_services"|wc -l) = 1 ]]; then
		print_center -ama 'PARANDO BADVPN'
		if [[ $(systemctl is-enabled $_services) = 'enabled' ]]; then
			systemctl disable $_services &>/dev/null
		fi
		systemctl stop $_services &>/dev/null
		del 1
		print_center -verd 'BADVPN PARANDO!!!'
		enter
		return
	fi

	title 'DETENER SERVICIOS BADVPN'
	all_service
	echo " $(msg -verd "[$n]") $(msg -verm2 '>') $(msg -azu 'PARAR TODOS')"
	back
	_opcion=$(selection_fun $n)
	[[ $_opcion = 0 ]] && return

	print_center -ama 'PARANDO SERVICIO BADVPN'

	while [[ $_opcion = $n ]] && read line; do
		if [[ $(systemctl is-enabled $line) = 'enabled' ]]; then
			systemctl disable $line &>/dev/null
		fi
		systemctl stop $line &>/dev/null
	done <<< $(echo "${serv_por[@]}")

	if [[ ! $_opcion = $n ]]; then
		if [[ $(systemctl is-enabled ${serv_por[$_opcion]}) = 'enabled' ]]; then
			systemctl disable ${serv_por[$_opcion]} &>/dev/null
		fi
		systemctl stop ${serv_por[$_opcion]} &>/dev/null
	fi

	del 1
	print_center -verd 'SERVICIO BADVPN PARADO'
	enter
}

del_port(){
	#_services=$(systemctl list-unit-files|grep badvpn|awk '{print $1}')
	_services=$(ls /etc/systemd/system |grep 'badvpn.')
	while [[ $(echo "$_services"|wc -l) -gt 1 ]]; do
		title -ama 'QUITAR PUERTOS BADVPN'
		all_service
		back
		_opcion=$(selection_fun $n)
		[[ $_opcion = 0 ]] && break
		viw_port=$(echo "${serv_por[$_opcion]}"|awk -F '.' '{print $2}')
		print_center -ama "REMOVIENDO BADVPN $viw_port"
		if [[ $(systemctl is-enabled ${serv_por[$_opcion]}) = 'enabled' ]]; then
			systemctl disable ${serv_por[$_opcion]} &>/dev/null
		fi
		systemctl stop ${serv_por[$_opcion]} &>/dev/null
		rm -rf /etc/systemd/system/${serv_por[$_opcion]}
		_services=$(ls /etc/systemd/system |grep 'badvpn.')
		del 1
		print_center -verd "BADVPN $viw_port REMOVIENDO"
		enter
	done
}

add_port(){
	title 'AGREGAR NUEVOS PUERTOS'
	IN_PORT
	msg -bar
	if [[ $(service_badvpn $PORT) = 'active' ]]; then
        print_center -verd 'PUERTO BADVPN AGREGADO'
    else
        print_center -verm2 'FALLA AL AGREGAR PUERTO BADVPN'
    fi
    unset PORT
    enter
}

menu_badvpn(){
	  echo -e "\e[1;93m    INSTALADOR BADVPN-UDPGW | SCRIPT LATAM"
	#_services=$(systemctl --all|grep badvpn|awk '{print $1}'|wc -l)
	_services=$(ls /etc/systemd/system |grep 'badvpn.'|wc -l)

	if [[ $(type -p badvpn-udpgw) ]]; then
		unset op1 op2 op3
                echo -e "\e[1;93m  [\e[1;32m1\e[1;93m]\033[1;31m > \e[1;97m DESINSTALAR BADVPN-UDPGW \033[0;31m] "  
                echo -e "\e[1;93m  [\e[1;32m2\e[1;93m]\033[1;31m > \e[1;97m INICIAR/REINICIAR BADVPN-UDPGW \033[0;31m] "      
                msg -bar
		_num=3
		if [[ $(systemctl list-units --all --state=active|grep badvpn|awk '{print $1}'|wc -l) -gt 0 ]]; then
                       echo -e "\e[1;93m  [\e[1;32m1\e[1;93m]\033[1;31m > \e[1;97m PARAR PUERTOS BADVPN-UDPGW \033[0;31m] "
			op1=$_num; let _num++
		fi
		msg -bar
		print_center -ama 'OPCIONES DE PUERTOS'
		msg -bar3
		echo " $(msg -verd "[$_num]") $(msg -verm2 '>') $(msg -azu 'AGREGAR PUERTO BADVPN-UDPGW')"
		op2=$_num
		if [[ $_services -gt 1 ]]; then
			let _num++
			echo " $(msg -verd "[$_num]") $(msg -verm2 '>') $(msg -azu 'QUITAR UN PUERTO BADVPN-UDPGW')"
			op3=$_num
		fi
	else
		echo " $(msg -verd '[1]') $(msg -verm2 '>') $(msg -verd 'INSTALAR BADVPN-UDPGW')"
		_num=1
	fi
	back
	opcion=$(selection_fun $_num)
	case $opcion in
		1)install;;
		2)restart;;
		"$op1")stop;;
		"$op2")add_port;;
		"$op3")del_port;;
		0)return 1;;
	esac
}

while [[  $? -eq 0 ]]; do
  menu_badvpn
done
