#!/bin/bash


keygen(){

x(){ openssl rand -hex $1 ; }

# creas la lista arq mediante con los archivos del script

script="/etc/SCRIPT"

key=`echo -e "$(x 5)-$(x 3)-$(x 3)-$(x 5)"`

list=`echo $key|awk -F "-" '{print $2 $3}'`

mkdir /var/www/html/LATAM

ls $script > /var/www/html/LATAM/$list



}

instalador(){

read -p $'\e[1;30mIngrese su key: ' kEy

list=`echo $kEy|awk -F "-" '{print $2 $3}'`

[[ ! -n $list ]] && echo -e "key invalida";return 0

wget -O $HOME/lista-arq http://1234.567.89:81/LATAM/$list &> /dev/null

[[ ! -s $HOME/lista-arq ]] && {
	echo -e "KEY INVALIDA"
	return 0
} || {
	for x in `cat $HOME/lista-arq` ; do
		wget -O ${SCPinstal}/$x https://raw.githubusercontent.com/darnixbot/layam/main/$x
		verify_arq "${SCPinstal}/$x"
	done
}

#ya descargaste los files sin tanto pedo
}
